Feature/modules
the-deep-nlp/core-server-infra pull request #2
Opened 2023-03-21 10:34 UTC by ranjan-stha

Added modules and handlers for Summarization, NGrams, TopicModeling. Also, added the mockserver.

2023-04-21 10:58 UTC, bewakes requested changes

2023-04-21 10:58 UTC, bewakes commented on handlers/ecs/geolocations/app.py
> +        self.bucket_name = os.environ.get("S3_BUCKET_NAME", None)
What is the purpose of using `.get(...) or None` vs `.get(..SECS, 86400)`? Why not `or` in both or default value in the function call itself?

2023-04-21 10:58 UTC, bewakes commented on handlers/ecs/geolocations/app.py
> +                    entries_data = json.loads(response.text)
We can probably use `response.json()` as well.

2023-04-21 10:58 UTC, bewakes commented on handlers/ecs/geolocations/app.py
> +            date_today = str(datetime.now().date())
Maybe use ISO format like: `date.isoformat()`? this will probably give more consistent result.

2023-04-21 11:01 UTC, aembryonic commented on handlers/ecs/geolocations/app.py
> +            date_today = str(datetime.now().date())
i think that str(DATE), or DATE.isoformat() will give the same result

2023-05-02 06:46 UTC, ranjan-stha commented on handlers/ecs/geolocations/app.py
> +                    entries_data = json.loads(response.text)
done.

2023-05-02 06:46 UTC, ranjan-stha commented on handlers/ecs/geolocations/app.py
> +            date_today = str(datetime.now().date())
done

2023-05-02 06:46 UTC, ranjan-stha commented on handlers/ecs/geolocations/app.py
> +        self.bucket_name = os.environ.get("S3_BUCKET_NAME", None)
done

2023-05-02 13:49 UTC, aembryonic commented
well done

2023-05-02 13:56 UTC, aembryonic reviewed
well done

2023-05-04 05:16 UTC, merged